version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # MongoDB est accessible sur le port 27017
    networks:
      - nba_network

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper
    depends_on:
      - mongodb
    networks:
      - nba_network
    command: ["scrapy", "crawl", "nba_spider"]

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: ["python", "app.py"]
    ports:
      - "5000:5000"  # Flask sera accessible sur localhost:5000
    depends_on:
      - mongodb
    networks:
      - nba_network

networks:
  nba_network:
